name: OIDC-MSDO-PROD-LINUX

# Controls when the workflow will run 
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # This runs the workflow every 30 minutes.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: security-devops-action
        uses: microsoft/security-devops-action@v1.10.0
        with:
          # The command to run. Defaults to run.
          command: run # optional, default is all
          # A comma separated list of analyzer to run. Example bandit, binskim, container-mapping, eslint, templateanalyzer, terrascan, trivy.
          tools: 'trivy' # please do not add more tools here, if you have to, please remove it once testing is done as this action runs every 30 minutes